- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/DB.java
This commits fixe the "getQueryProvider" of DBImpl. Without this change, we were unable to work with the custom query.
What do you think @MAAARKIN and @filipegermano ?
> Bugfixed getQueryProvider

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBImpl.java
Hi,
This commits fixe the "buildPage" of DBImpl. These changes correct the paging control flags, for example, the hasNextPage flag. Remember that paging starts with the zero value.
What do you think @MAAARKIN and @filipegermano ?
> heimdall/gateway/filter/helper/DBImpl: buildPage's flags fixed.

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OperationService.java
The double wild card validation method is not allowing the creation of paths that have no wild cards.
That is not how it is supposed to work.
Valid paths are:
* paths with no wild card
* paths with double wild card at the end
This change fixed the issue #38
> Fixed double wild card validation

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/appender/MongoDBAppender.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/appender/MongoDBAppender.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/Trace.java
Currently its possible add the request **trace** to mongodb if the properties is enabled. But if the mongo properties in the application.yml was configured with mongo URI connection the MongoAppender.java was not connecting because was not configured with MongoClientURI.
This PR make more flexible the application to sync the mongodb middlewares and MongoAppender (SL4J) to use same database but different collections
@thiagonego now we put the trace json in mongodb and now its possible to planning an Api to consulting the traces in database and provide an view to see all traces in front-end
> Fix Req/Res Trace to save on MongoDB

- heimdall-frontend/src/containers/Operations.js
When all the resources were opened in the front end and clicked to add some operation, this operation was always saved in the last resource because they were showing all the forms of the operations due to the visibility state of the modal was shared in redux.
1. Go to api
2. Click on tab Resources
3. Open all tab-accordion Resources
4. Click on AddOperation of the first Resource and save Operation
5. See error
The operations must be registered in their respective Resource
**Desktop:**
- OS: Windows 10
- Chrome
- Version  66.0.3359.181 (64 bits)
**To fix I do**
Removed modal visibility state from redux. Now available only inside Operations Component.
> Fixed bug when creating an operation using the frontend.

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/enums/Status.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/environment/Property.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/MiddlewareService.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/MiddlewareServiceTest.java
Added a feature that gives the user the ability to set a Middleware the `DEPRECATED` status.
This status indicates that the middleware has a issue or is too old to be used.
This only applies to the versions of the same middleware.
Along with this status there is are two new properties that can be set in the `application.yml` :
```
middleware:
allowInactive: Integer
deleteDeprecated: Boolean
```
---
Handles how many middlewares should stay inactive, here is how it works.
When adding a new middleware:
* If not set or set to 0
* Set the active middleware to inactive and add the new middleware
* The status of all other middlewares will not be changed
* If set to `n`
* Set the active middleware to inactive and add the new middleware
* The status of the first `n` inactive middlewares will not …
> Middleware handling

- heimdall-config/src/main/resources/shared/application.yml
Default behavior should be not to delete deprecated middlewares to keep backwards compatibility
> Should not delete deprecated

- heimdall-frontend/src/components/interceptors/DnDInterceptorType.js
- heimdall-frontend/src/components/interceptors/InterceptorForm.js
- heimdall-frontend/src/containers/Interceptors.js
When an interceptor was added and saved locally on the frontend and tried to edit then the interceptor duplicate only in view.
1. Go to API's
2. Click on tab Interceptors
3. Select some operation
4. Drag and drop some interceptor type (circles above the drag area) and save it only by clicking on the button "Save" of the modal
5. Drag and drop the interceptor create again to edit
6. Update some attribute and save
7. See error
When editing a local interceptor, the same information must be updated without duplicate the interceptor.
**Desktop (please complete the following information):**
- OS: Window 10
- Browser: Chrome
- Version: 67.0.3396.62 (64 bits)
**To fix I do**
When an interceptor is …
> Fix bug duplicate interceptor

- heimdall-frontend/src/components/environments/EnvironmentForm.js
- heimdall-frontend/src/components/environments/ListVariablesEnvironment.js
- heimdall-frontend/src/containers/Operations.js
After the #45  the variables now is required when a new environment will be created. But variables are optional so they will be required only when the user put to add a new variable.
with this PR i provide a new button to add variable when no have variables. When the user click on the add Button the inputs will show and now the required input will work correctly.
> *Fix a bug when try to create a new environment without variables.

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/JsonImpl.java
**The bug**
When the user will add a Mock Interceptor with the response body is a json array, the backend validation not accept the array like a valid json.
1. Go to 'Api'
2. Click on 'Interceptors tab'
3. Add a Mock interceptor
4. Put some array json in the body, click on save
4. See error
**What i do**
*Fix parser/validation when the input json is an array on Mock Interceptor;
*Fix indentation to default;
Now, when the user put a Mock with the response with a Json array in the body, the response will show correctly the json array
> [BUG] Fix parser/validation when the input json is an array on Mock Interceptor;

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/TraceConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CorsFilter.java
*Fix cors problem when the backend send cors too.
When the backend send the cors implementation then the heimdall add headers to the response duplicating the headers necessary, with this PR we check if the header are present in the response and if true we don't put the CORS implemented by heimdall to the response
> Fix cors duplicated

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/ProviderResource.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OAuthService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsPath.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/JwtUtils.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/OAuthInterceptorService.java
Implementation of the add objects in payload of a token JWT, when  it sends a request to OAuth GENERATE, add javadoc and show error when client_id is not found in request to OAuth AUTHORIZE.
> Add objects in payload of the token

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/StartServer.java
During Gateway startup the log shows:
* "Initializing Goovy Interceptors"
Should be:
* "Initializing Groovy Interceptors"
> [Grammarfix] Fixed misspelled "groovy" in log for listener

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/spec/Json.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/spec/StackTrace.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/LocalDateTimeSerializer.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/GeneralTrace.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/Trace.java
The way that Heimdall saved the date for the logs was not ISO 8601-compliant. That meant that searches with mongodb were not correct.
This pull request makes sure that the date is saved correctly in mongodb
> Date serialization

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/ApiService.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/ApiServiceTest.java
- heimdall-frontend/src/components/apps/AppForm.js
**Describe features**
Restrict adding environments with equal inbound url when create or update any api.
> Restrict adding environments with equal inbound url in API

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
The method to remove headers from Helper class that is used by the middlewares was not working properly.
The issue was a wrong condition. It was the _not_ before the check that was causing the problem.
Also replaced `.findFirst().isPresent()` for a `.anyMatch` to improve readability.
> Remove header from middleware helper not working

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
- heimdall-middleware-spec/pom.xml
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/ApiResponseMockImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/CallMockImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/DBMockImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/HelperMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/HttpMockImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/JsonMockImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/XmlMockImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/EnvironmentMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/HeaderMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/InfoMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/QueryMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/RequestMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/ResponseMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/StackTraceMock.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/TraceMock.java
1. Changes in `heimdall-middleware-spec` 
* Created a Mock implementation for the Helper class used by the middlewares to provide an easier way to unit test the middleware.run() method. With this pull request the middleware developer can use a Mock framework like Mockito with ease.
2. Changes in `heimdall-gateway` 
* `DBMongoImpl` -  removed redundant checks
* `HttpImpl` - refactored to improve readability
> Helper mock

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/TraceConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/Trace.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/TraceContextHolder.java
**Bug Fix**
Calls made to the health check (/manager/health) were showing up in the logs.
This behaviour happens because the `shouldPrint` variable is not thread safe.
To fix that the controller variable `shoudPrint` was moved to the `Trace` class as it is a instance variable.
> Traces logging /manager/**

- heimdall-frontend/src/components/traces/ListTraces.js
**Bug fix**
In the Trace page the button to show more details has a tooltip with the label "Edit" when it should be "View".
> Trace view tooltip with wrong title

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
The method sendDelete wasnt handling headers. So, when a request was made using this method the headers were ignored.
This pull request solves this issue.
> Changing the sendDelete method.

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/Trace.java
This pull request adds the ability to log multiple types of responses differently.
Logs are treated depending on their response code in the following manner.
* 1xx to 2xx range = level INFO
* 3xx to 4xx range = level WARNING
* OTHER = level ERROR
> Added multiple log levels

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/repository/InterceptorRepository.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OperationService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/ResourceService.java
**Describe the feature**
A Operation can have Interceptors attached to it, so when deleting a Operations all the Interceptors attached must be deleted aswell.
The same goes for Resources that can have either Interceptors or Operations with or without Interceptors. So when service must delete all its children when deleting the parent.
This pull request treats this sort of scenario in the back end. The front end must warn the user when using any of these services.
> Properly delete resources with operations and interceptors

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/SecurityService.java
- heimdall-gateway/src/main/resources/template-interceptor/access_token.mustache
- heimdall-gateway/src/main/resources/template-interceptor/client_id.mustache
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilterTest.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/service/SecurityServiceTest.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/util/RouteSortTest.java
The client id verification would allow a a request with a invalid client id to go through.
The error was caused by a misplaced verification in the SecurityService class that caused a nullpointer exception that was not properly handled.
> [BUGFIX] clientId verification

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-config/src/main/resources/shared/gateway.yml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/HeimdallHandlerMapping.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomHostRoutingFilter.java
- pom.xml
*Ignoring "/manager/**" in zuul
*Rollback the spring cloud and gateway to keep the same code based on version 1.2.2
> Keep the same code based on version 1.2.2

- heimdall-api/src/main/resources/bootstrap-docker.yml
- heimdall-api/src/main/resources/bootstrap.yml
- heimdall-config/src/main/resources/shared/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/environment/Property.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/appender/MongoDBAppender.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
- heimdall-gateway/src/main/resources/bootstrap-docker.yml
- heimdall-gateway/src/main/resources/bootstrap.yml
**HOT-FIX**
1. Wrapped MongoDBAppender with a AsyncAppender to make it mo resilient to mongodb failures
This prevents Heimdall to stop answering and queue requests if the connection to the MongoDB drops.
2. Api and Gateway should not check the config's health
When performing their health check the Api and Gateway have no need to check the Config's health.
> [HOT-FIX] Mongo to use AsyncAppender and removed config health

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/HeimdallHandlerMapping.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/Middleware.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/MiddlewareListener.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/StartServer.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/util/HeimdallFilterFileManager.java
This pull request solves two issues related to new Api and new routes creation.
This is a long time problem that Heimdall had. Under some circumstances request would not pass through any of the filters. Even paths that are correct would not work. Only a restart of the gateway would fix that.
That was caused by the routes not being registered properly. Now the initial routes are registered at the start of the application. This change should prevent that problem from happening in the future.
There was a issue that prevented a middleware to work when attached to a new Api.
**Steps to reproduce**
1. Create a Api
2. Create Resource and Operation
3. Add a middleware to this Api
4. Add a interceptor to the new Operation to use the new Middleware
5. Call the operation (see error)
Restart the …
> Filters not being registered

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Response.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/call/ResponseMock.java
When a middleware received a file from the backend Heimdall would not set the response correctly.
1. Create a middleware that consumes an Api that returns a file
2. Try to consume this resource
3. The downloaded file would come back empty from Heimdall even if the backend was working correctly.
Heimdall should not interfere with a file download.
> [HOTFIX] Middleware file response not working

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Http.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/HttpMockImpl.java
**On this pull request:**
- Adding the sendPatch() method to the Http interface and its respective implementation in HttpImpl, so that the architecture supports the call of requests through the HTTP PATCH method;
- Modifying the RestTemplate object to support new Http methods, such as PATCH.
> Adding HTTP PATCH method support

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/interceptor/impl/CacheClearHeimdallInterceptor.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/CacheService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/TemplateUtils.java
- heimdall-frontend/src/utils/InterceptorUtils.js
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/CacheInterceptorService.java
- heimdall-gateway/src/main/resources/template-interceptor/cache_clear.mustache
Cache invalidation was would not delete all caches from a path if it had multiple calls with different headers/queryparams. That might couse some caches not to be deleted when they should.
Now the invalidation will clear all caches at once, preventing that problem.
> Cache interceptor refactoring

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/ApiService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OperationService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/StringUtils.java
- heimdall-frontend/src/components/apis/ApiDefinition.js
- heimdall-frontend/src/components/apis/NewApiOverview.js
- heimdall-frontend/src/components/operations/OperationForm.js
- heimdall-frontend/src/containers/Operations.js
- heimdall-frontend/src/containers/Resources.js
Changes have been made to the Operation path and Api base path verification in the back end and in the front end to make the new rules clearer to the users.
* Back end
* Added method to enforce this list of rules to a Operation path and an Api basepath:
* always start with a forward slash 
* can not have multiple forward slashes together ( "//" )
* can not have a forward slash at the end
* Front end
* OperationForm now shows the Api base path as a prefix of the Operation path field.
* ApiDetails page and Api creation page now show the base path forward slash in the base path field.
> Operation path and Api base path refactoring

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/LifeCycleService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/LifeCycleService.java
- heimdall-gateway/src/main/resources/template-interceptor/access_token.mustache
- heimdall-gateway/src/main/resources/template-interceptor/blacklist_ip.mustache
- heimdall-gateway/src/main/resources/template-interceptor/cache.mustache
- heimdall-gateway/src/main/resources/template-interceptor/cache_clear.mustache
- heimdall-gateway/src/main/resources/template-interceptor/client_id.mustache
- heimdall-gateway/src/main/resources/template-interceptor/custom.mustache
- heimdall-gateway/src/main/resources/template-interceptor/identifier.mustache
- heimdall-gateway/src/main/resources/template-interceptor/middleware.mustache
- heimdall-gateway/src/main/resources/template-interceptor/mock.mustache
- heimdall-gateway/src/main/resources/template-interceptor/oauth.mustache
- heimdall-gateway/src/main/resources/template-interceptor/ratting.mustache
- heimdall-gateway/src/main/resources/template-interceptor/whitelist_ip.mustache
This pull request fixes a couple of bugs:
1. During the PLAN lifecycle verification it did not validate if the plan was had Status ACTIVE
1. During the PLAN lifecycle the verification of the patters used a String.contains method when it should be a PathMatcher.match method. This could cause a error when there was two Api's configured as follows.
* Api 1:
* basepath: /foo
* Api 2:
* basepath: /bar
* operation: /foo
If a Plan interceptor is attached to Api 1, it would run when a call was made to the Api 2 /bar/foo
> HOTFIX - Plan verification

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogResponseFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/LifeCycleService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/SecurityService.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/service/SecurityServiceTest.java
*Actually when somebody put a interceptor with a PLAN lifecycle and don't put a valid client_id (app) then throw a Null Point Exception, this PR will fix this;
*Fix the problem when the log filter read the response headers, now we first check the zuulResponseHeader s and after that we check the servlet response headers
> Fix plan lifecycle and log blacklist write

- heimdall-api/pom.xml
- heimdall-core/pom.xml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/interceptor/LogMaskDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/enums/TypeInterceptor.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/interceptor/impl/LogMaskerHeimdallInterceptor.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/TemplateUtils.java
- heimdall-gateway/pom.xml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/LogMaskerService.java
- heimdall-gateway/src/main/resources/template-interceptor/log_masker.mustache
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/service/LogMaskerServiceTest.java
Since the PR #130 the log interceptor is now a built in filter and its executed for all requests and writes the body, headers and uri to the request and response objects in the trace.
This new interceptor adds a new option to mask the logs, that way the user can chose to remove the body, the uri or any of the headers, or all, from the trace information.
Usage, examples with the interceptor content:
* Delete the body from the request
```json
{
"body": true
}
```
* Delete the body and two headers
```json
{
"body": true,
"headers": true,
"ignoredHeaders": [
"someHeader", "anotherHeader"
]
}
```
* Delete the uri and all header but not the body
```json
{
"uri": true,
"headers": true
}
```
> Log masker interceptor

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-frontend/src/styles.less
* When registering two or more interceptors with wrong contents, the error message shown is always the same as the first one;
* When there is scroll in the body, the linear-gradient in background is not fixed. 
1. Go to Apis
2. Click on some API
3. Select tab Interceptors
4. Create a interceptor with content wrong and save
5. Create other interceptor of different type with wrong content and save
6. See error 
The second error message should show the template for the correct interceptor.
> Hotfix - Popup error message might show wrong template

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/environment/Property.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/MongoLogConnector.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/appender/MongoDBAppender.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
Changed the way that Heimdall saves the timestamp to mongodb so it can be formatted for timezones.
> Mongo date optimization

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/OperationResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/ResourceResource.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/amqp/AMQPRouteService.java
The `br/com/conductor/heimdall/core/service/amqp/AMQPRouteService` class had duplicated methods
Removed one and factored out all uses of it.
> Removed duplicated method from AMQPRouteService

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OAuthService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/JsonImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/OAuthInterceptorService.java
PR #124  added a constraint between the OAuth privatekey and an App's client_id. This constraint should not exist, this PR fixes that among other fixes to better handle error in the requests.
Also fixed Json validation by JsonImpl class. There was an error that cause the validation to return true when an trailing comma was left at the end of an json.
Eg.:
Valid json
```json
{
"key": "value"
}
```
Invalid json that was being tagged as valid
```json
{
"key": "value",
}
```
Now it is correctly marked as invalid.
> OAuth privatekey/client_id constraint

- heimdall-gateway/pom.xml
Actually with the breakline in the pom, we can't upload the dockerfile to docker hub.
> *Fix the breakline in the pom to solve the problem with docker plugin.

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
AccessToken was being wrongly saved as client_id to trace
> [BUGFIX] Client Id was being saved incorrectly to trace

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/ScopesFilter.java
When scopes are not set the verification would fail if a valid client_id was used
> [BUGFIX] Scopes filter fix

- heimdall-core/src/main/resources/liquibase/changelog/20181203115559-update-table-provider-with-provider-default.xml
- heimdall-core/src/main/resources/liquibase/changelog/20190128114155-recreate-table-oauth-authorizes.xml
- heimdall-core/src/main/resources/liquibase/master.xml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/OAuthInterceptorService.java
**Describe Hoffix**
* The original liquibase script that created the OAUTH_AUTHORIZE did not specified the contraints names, that caused the deletion of the client_id contraint to not work properly with multiple diferent databases
* The Implicit flow did not authorized with the provider for the first request
* The client id validation was not occuring for password and implicit flows
**What was done**
* Created a new liquibase script that recreates the OAUTH_AUTHORIZE table and adds the constraints names
* Factored out the provider validation to a method that is used by all OAuth flows methods
* Created client_id validation method to be used by all OAuth flows methods
> Hotfix OAuth

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
The AccessToken interceptor should be allowed at the Plan LifeCycle.
This bug was introduced by PR #197
> AccessToken interceptor should be allowed at Plan lifecycle

- heimdall-gateway/src/main/resources/template-interceptor/middleware.mustache
The middleware template should let the request continue if it is set by a middleware.
The template now has a default response if a middleware throws an exception
> [HOTFIX] - Middleware template

- heimdall-frontend/src/components/interceptors/DnDInterceptor.js
- heimdall-frontend/src/containers/Resources.js
It is not possible to add a new Resource after editing an existing one.
1. Go to one Api
2. Click on Resources
3. Edit a existing Resource
4. Try to create a new Resource
5. See error
The user should always be able to create a new resource.
---
The popover that shows when clicking in a intercetor does not disapear after deleting a interceptor.
1. Navigate to the interceptors editing page
2. Add at least two interceptors
3. Click on the leftmost interceptor and delete it
4. See error
The popover should disapear after the deletion of a interceptor.
> Bug in Resource and Interceptors

- heimdall-api/pom.xml
- heimdall-core/pom.xml
- heimdall-gateway/pom.xml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/JsonImpl.java
- heimdall-middleware-spec/pom.xml
- pom.xml
**Describe Bug**
If a json object has a string that contains backslashes, the Mapper would add a second backslash as an escape character for the java string.
**Describe Hotfix**
This PR adds the use of StringEscapeUtils.unescapeJava() method to prevent that behaviour.
> Json parse backslash

- heimdall-api/pom.xml
- heimdall-core/pom.xml
- heimdall-core/src/main/resources/liquibase/changelog/20190222142000-recreate-default-plan-column.xml
- heimdall-core/src/main/resources/liquibase/master.xml
- heimdall-gateway/pom.xml
- heimdall-middleware-spec/pom.xml
- pom.xml
Currently the startup project on empty PostgreSQL fail because the liquibase crash on conditions specifically to SQLServer, with this PR I fix this case and now we can startup the project with PostgreSQL or SQLServer without problem.
> Fix liquibase startup

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogRequestFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogResponseFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/ScopesFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/FilterDetail.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/StackTraceImpl.java
During the logging process the stacktrace from a filter of another request would still be logged on another successful request. That happens because the FilterDetail object inside HeimdallFilter was not being reset for each request.
This PR solves this issue.
> Reset FilterDetail from HeimdallFilter

- heimdall-api/pom.xml
- heimdall-core/pom.xml
- heimdall-gateway/pom.xml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImplTest.java
- heimdall-middleware-spec/pom.xml
- pom.xml
Described on #241 
Added a map to keep the query params. When a request method is used, the map will be passed to an existing `uriComponentsBuilder`.
> Fixing queryParams issues

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/Trace.java
- heimdall-frontend/src/components/interceptors/DropClientInterceptors.js
Interceptor badge position was broken. To fix that I have replaced the ant-badge-count class for a proper CSS style.
Added the cache element to the Trace class. That means it is now visible in the front end.
> Interceptor badge fix

- heimdall-api/src/main/resources/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/Trace.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/trace/FilterDetail.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/failsafe/CircuitBreakerHolder.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CacheWriterFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CorsPostFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomHostRoutingFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomSendResponseFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogRequestFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogResponseFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/ScopesFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/FilterDetail.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/Trace.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/filter/ScopesFilterTest.java
Changed the way that the filters are saved in the trace
The filters were saved with a property name inside them. This has been factored out. This provides more flexibility for logging indexing.
Old trace:
```json
}
"name": "HeimdallDecorationFilter",
"timeInMillisRun": 107,
"timeInMillisShould": 0,
"status": "SUCCESS",
"totalTimeInMillis": 107
}
```
New Trace:
```json
"HeimdallDecorationFilter": {
"timeInMillisRun": 107,
"timeInMillisShould": 0,
"status": "SUCCESS",
"totalTimeInMillis": 107
}
```
> Trace filter change

- heimdall-middleware-spec/src/test/java/br/com/conductor/heimdall/middleware/util/helpermock/call/RequestMockTest.java
Hi,
I've analysed your code base and noticed that:
`br.com.conductor.heimdall.middleware.util.helpermock.call.RequestMock` 
in the heimdall-middleware-spec module is not fully tested.
I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
> Add unit tests for helpermock.call.RequestMock

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/router/EnvironmentInfoRepository.java
The environments list query could return an empty list. That would cause an exception to be thrown.
This PR adds a check before retrieving the environment.
> Fixed a bug when the environments query returns an empty list

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/AccessTokenInterceptorService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/ClientIdInterceptorService.java
Fixed the way that the ClientIdInterceptorService and AccessTokenInterceptorService fetch the access_token and client_id headers.
The priority is for the headers set via a Custom interceptor, this allows the user to override any client_id or access_token sent in the original request. If no such interceptor exists, the headers from the original request is used.
> ClientId and AccessToken headers

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
It should only try to get the header from ZuulRequestHeaders if it fails to get from HttpServletRequest.
> Fixed header.get() method

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/Plan.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/repository/PlanRepository.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/PlanService.java
- heimdall-frontend/src/actions/plans/index.js
The actual scenario does not show a message to the user that it's not possible to remove a Plan attached to an App and also holds an infinite loading icon.
This pull request do:
- Show a popup error message to the user.
- Remove the infinite loading icon.
- Prevent the constraint error from API side.
> Fixed bug when trying to delete a plan associated to an App

- heimdall-api/pom.xml
- heimdall-core/pom.xml
- heimdall-frontend/src/utils/InterceptorContentUtils.js
- heimdall-frontend/src/utils/InterceptorUtils.js
- heimdall-gateway/pom.xml
- heimdall-middleware-spec/pom.xml
- pom.xml
**Describe Hotfix**
* Its is not possible to create interceptors of type Mock, Ratting, AccessToken, ClientId, OAuth, CacheClear, and Cors, because their content needs to be stringfied before the request is sent to the API.
**The fix**
* Created another function that returns the stringfied content and renamed the `defaultContent` function to `simpleContent` that is still used by Middleware and Custom interceptors.
> Stringify Content in some interceptors

- heimdall-frontend/src/components/interceptors/InterceptorForm.js
This pull request fixed the actual scenario which throws a TransientPropertyValueException when trying to edit an interceptor associated to an environment.
> Fixed TransientPropertyValueException when updating Interceptor

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
The actual scenario allows the user create a middleware without an operation.
This behavior prevents user delete that middleware throwing a NullPointerException on the API side when trying to delete. 
This pull request is to not permit user create a middleware without an operation.
> Fixed NullPointerException when delete middleware without operation

- heimdall-frontend/src/components/operations/OperationForm.js
- heimdall-frontend/src/containers/Operations.js
This pull request fixes two problems on operation modal:
- No warning is shown when user tries to add an operation without fill required fields and a infinite Loading button appears.
- When a Bad Request (400) is sent to API, the returned error message is not shown on alert component.
> Fixed bug on Add Operation Modal

- heimdall-frontend/src/utils/InterceptorContentUtils.js
This pull request fix a bug at Log Masker when the API receives an empty string instead receive a empty list.
> Fixed LogMasker ignored headers bug

- heimdall-frontend/src/components/apps/AppForm.js
This pull request is to remove the loading button on AppForm which holds to infinite if no plan is registered.
> Removing infinite loading button on AppForm

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/MiddlewareService.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/MiddlewareServiceTest.java
Deprecation of middlewares was trying to set the file to null in the database, but the column `file` has a not null constraint. Furthermore, this is not the correct behaviour, the entry should be completely deleted from the database. This PR fixes that.
> Middleware depreciation fix

- api/src/main/java/br/com/conductor/heimdall/api/configuration/SecurityConfiguration.java
This pull request is to avoid 403 forbidden error on '/manager/info' spring actuator endpoint.
> Fix '/manager/info' 403 Forbidden error

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/MiddlewareService.java
**Describe bug**
If middlewaremap attribute not contains some Status (Active, Inactive or Deprecated) when is called get("status"), this method return null and consequently throw NullPointerException when used.
> Fix null pointers exceptions

- heimdall-frontend/src/components/interceptors/wrappers/Cors.js
**Describe Hotfix**
The content from props not have attribute cors, so when is called "content.cors" undefined is returned, because content is the Cors Object now.
> Fix cors undefined in front-end
