- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/OperationSort.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/util/RouteSort.java
The sorting of the paths for Operations and ZuulRoute can be done using the Paths package.
> Refactored path sorting to use Paths package

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/configuration/DataBaseConfiguration.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/AccessTokenResource.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/AccessTokenService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/AppService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsInterceptors.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/AccessTokenServiceTest.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/InterceptorFileService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/SecurityService.java
- heimdall-gateway/src/main/resources/template-interceptor/access_token.mustache
- heimdall-gateway/src/main/resources/template-interceptor/client_id.mustache
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Call.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Info.java
* Including API validation on client_id and access_token interceptor
* Clean caches in appService update and delete
* Clean caches in accessTokenService update and delete
* Removal business rule of client_id and access_token interceptor templates
> Improved validation of clint_id and access_token interceptors

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/OperationSort.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/util/OperationSortTest.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/util/RouteSort.java
* Fixed OperationSort and RouteSort
* Added more test cases for the RouteSort
* Created tests for OperationSort
> Sorting route operation

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/DBMongo.java
bufixed ref #11 and #21 into DBMongoImpl
> heimdall/gateway/filter/helper/DBMongoImpl: Bugfixed getQueryProvider and buildPage.

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/ApiService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OperationService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
Added validation for Operation paths to match the following criteria for allowed paths.
* any path that has no wild card
* paths that end with double wild card
Any path that do not follow those rules will generate a exception.
> Wildcard validation

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
Adjustment in paging calculation in DBMongoImpl
> Adjustment in paging calculation in DBMongoImpl

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/TraceConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Request.java
Added getUrl method to Helper Request
Fix Method helper.request().query().getAll()
> Fix query getAll and added getUrl to request

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Http.java
Currently the body method only receives a Map, but there is a need to send String.
this PR reference #34
> Added new implementation of body method for sending String

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
Corretion Pagination Calculation
#36
> Corretion Pagination Calculation

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/interceptor/OAuthDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/request/OAuthRequest.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/OAuthAuthorize.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OAuthService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/JwtUtils.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/TemplateUtils.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/InterceptorFileService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/OAuthInterceptorService.java
- heimdall-gateway/src/main/resources/template-interceptor/oauth.mustache
This pull request is reference the issue #50
> Add privateKey to be informed in creation the InterceptorOAuth

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/configuration/RabbitConfiguration.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/amqp/AMQPCacheService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/RabbitConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/CacheListener.java
*Fix problems with queue's;
*Only gateway will generate queue's
*Api only will produce messages
*Only gateway will register the exchanges.
> Provide a new way to create Rabbit Queues to improve better performance

- heimdall-frontend/src/containers/Interceptors.js
- heimdall-frontend/src/utils/ColorUtils.js
**Describe the feature**
Add a tag (Http Method) to operation's dropdrown inside interceptors.
> Add a tag (Http Method) to operation's dropdrown

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CorsFilter.java
*Updating cors filter to extends ZuulFilter to force the execution when middleware supress the routing
> Fix cors duplicated

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/TracesResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/util/ConstantsPrivilege.java
- heimdall-api/src/main/resources/liquibase/changelog/20180614173243-insert-privileges-to-logtraces.xml
- heimdall-api/src/main/resources/liquibase/master.xml
- heimdall-core/pom.xml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/LogTraceDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/PageDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/TraceDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/page/LogTraceDTOPage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/page/LogTracePage.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/LogTrace.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/Trace.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/TraceService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/spec/Json.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/spec/StackTrace.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/trace/FilterDetail.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/trace/GeneralTrace.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/trace/RequestResponseParser.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsPath.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsTag.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/MongoLogConnector.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/Page.java
Created connection and back-end infrastructure to read the logs Heimdall saves in MongoDB.
Service, resouce, entities and dtos added to make the connection with the logs.
> Trace Resource

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/enums/HttpMethod.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/enums/InterceptorLifeCycle.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilterTest.java
**Describe the feature**
Added method ALL to be accepted when any request method is received with Tests and refactored duplicate code.
> Add http method ALL

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/App.java
- heimdall-frontend/src/components/apps/AppForm.js
- heimdall-frontend/src/containers/SingleApp.js
- heimdall-frontend/src/utils/ColorUtils.js
Show list of accessTokens from an App when editing an App on Heimdall front-end.
> Show list of accessTokens from an App

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/TracesResource.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/TraceService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/MongoLogConnector.java
Fixed a bug that caused the url pattern filter to not work.
Also prevented MongoLogConnector to create multiple connections to mongodb.
> BUGFIX - Url pattern not working properly

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/TracesResource.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/logs/FiltersDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/logs/LogTraceDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/logs/TraceDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/TraceService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/CalendarUtils.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/MongoLogConnector.java
Changed the trace resources to work with a list of filters.
> Adjusted trace resource to performe searches based on a list of filters

- heimdall-frontend/package-lock.json
- heimdall-frontend/package.json
*Fix some problems generated by Less when the version is more higher than 2.7.3
> Fix inline javascript

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/interceptor/IpsDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/enums/TypeInterceptor.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/InterceptorFileService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/IpsInterceptorService.java
- heimdall-gateway/src/main/resources/template-interceptor/blacklist_ip.mustache
- heimdall-gateway/src/main/resources/template-interceptor/whitelist_ip.mustache
**Describe the features**
Add Blacklist and Whitelist interceptors.
* Blacklist interceptor
When this interceptor is added, the user can provide a list of ips which the requests will be blocked by Heimdall, request from any other ip will be allowed to pass.
* Whitelist interceptor
It is the opposite of the Blacklist interceptor. Will only allow requests from whitelisted ips, any other ip will be blocked
> Blacklist and Whitelist interceptors

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/repository/OperationRepository.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/OperationService.java
*Fix validation problems when somebody update an operation that path was present in different api too.
> *Fix validation problems when somebody update an operation

- changelog.md
Created changelog file to keep track of changes between releases
> Created Heimdall changelog documentation

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
Remove validation with br.com.twsoftware.alfred.object.Objeto to create Page result from search in MongoDb.
> Remove validation with br.com.twsoftware.alfred.object.Objeto.

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Http.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/HttpMockImpl.java
Method to allow custom creation of RestTemplate object
This pull request fixes the issues with #83
> Provided a way to create a custom RestTemplate for the http requests

- heimdall-frontend/src/actions/environments/index.js
- heimdall-frontend/src/containers/Resources.js
- heimdall-frontend/src/containers/SingleEnvironment.js
* Add notifications in SingleEnvironments and dispatch event when updating and deleting a environment;
* Add notifications in Resources.
> Notifications

- changelog.md
- heimdall-frontend/src/components/developers/ListDevelopers.js
- heimdall-frontend/src/components/environments/ListEnvironments.js
- heimdall-frontend/src/components/plans/ListPlans.js
- heimdall-frontend/src/components/users/ListUsers.js
- heimdall-frontend/src/styles.less
* Adding scroll in tables;
* Update list of the environments.
> Adding scroll in tables and update list of the environments.

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/DataBaseConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomHostRoutingFilter.java
- pom.xml
**Description**
Updating Spring Cloud version from Dalstron.SR4 to Edgware.SR4.
> Update spring cloud version

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/JsonImpl.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/Json.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/JsonMockImpl.java
> Implementação de parse json com TypeReference possibilitando o parse de objetos com generics

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/InterceptorFileService.java
- heimdall-gateway/src/main/resources/template-interceptor/ratting.mustache
The RateLimit interceptor is supposed to limit the amount of requests. This interceptor can be attached to a Plan, Resource or Operation.
There was a bug that prevented the interceptor to create and use the correct key to the RateLimit repository. This pull request solves this issue.
> [BUGFIX] RateLimit Interceptor

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
- pom.xml
DiscardingThreshold isn't required into asyncappender by default.
> DiscardingThreshold not required.

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CacheWriterFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomSendErrorFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomSendResponseFilter.java
Now the error request will not be dispatched to Spring error controller, the response will write in the same request
> Fix error response

- heimdall-frontend/src/components/access-tokens/AccessTokenForm.js
- heimdall-frontend/src/components/apis/ApiDefinition.js
- heimdall-frontend/src/components/apis/Index.js
- heimdall-frontend/src/components/apis/NewApi.js
- heimdall-frontend/src/components/apis/NewApiResources.js
- heimdall-frontend/src/components/apis/ResourceOperationForm.js
- heimdall-frontend/src/components/apis/SingleResource.js
- heimdall-frontend/src/components/apps/AppForm.js
- heimdall-frontend/src/components/developers/DeveloperForm.js
- heimdall-frontend/src/components/environments/EnvironmentForm.js
- heimdall-frontend/src/components/interceptors/DnDInterceptor.js
- heimdall-frontend/src/components/interceptors/DnDInterceptorType.js
- heimdall-frontend/src/components/login/LoginForm.js
- heimdall-frontend/src/components/plans/PlanForm.js
- heimdall-frontend/src/components/ui/FloatButton.js
- heimdall-frontend/src/components/users/UserForm.js
- heimdall-frontend/src/containers/AccessTokens.js
- heimdall-frontend/src/containers/Apps.js
- heimdall-frontend/src/containers/Developers.js
- heimdall-frontend/src/containers/Environments.js
- heimdall-frontend/src/containers/Interceptors.js
- heimdall-frontend/src/containers/Middlewares.js
- heimdall-frontend/src/containers/Operations.js
- heimdall-frontend/src/containers/Plans.js
- heimdall-frontend/src/containers/Resources.js
- heimdall-frontend/src/containers/Traces.js
- heimdall-frontend/src/containers/Users.js
* Adding id identifier to buttons that save, cancel or add something
> Adding id identifier to buttons

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/MetricsResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/util/ConstantsPrivilege.java
- heimdall-api/src/main/resources/liquibase/changelog/20180918144230-insert-privileges-for-logtraces.xml
- heimdall-api/src/main/resources/liquibase/changelog/20180918144310-insert-privileges-for-metrics.xml
- heimdall-api/src/main/resources/liquibase/master.xml
- heimdall-config/src/main/resources/shared/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/metrics/Metric.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/enums/Periods.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/MetricsService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/MiddlewareService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsPath.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsTag.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/MongoLogConnector.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/Pageable.java
**Main changes**
Created the metrics structure with a few initial metrics.
All metrics will be extracted from the logs that Heimdall saves on mongoDB.
**Minor changes**
Middleware and traces listing now returns a sorted list in descending order.
> Metrics Resource

- heimdall-api/pom.xml
*Fix api final version naming, used to deploy on docker
> Docker parameters

- heimdall-frontend/src/components/ui/FloatSearch.js
- heimdall-frontend/src/containers/Interceptors.js
- heimdall-frontend/src/containers/Operations.js
* Filter operations with regex in resources and interceptors.
> Filter operations in resources and interceptors

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/JsonImpl.java
Fit to make Json parse case-insensitive
> Fit to make Json parse case-insensitive

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/configuration/CORSFilter.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/MiddlewareResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/util/ZipUtils.java
- heimdall-frontend/src/actions/middlewares/index.js
- heimdall-frontend/src/containers/Middlewares.js
- heimdall-frontend/src/services/MiddlewareService.js
- heimdall-frontend/src/utils/FileUtils.js
Middleware file download through the front-end would corrupt the downloaded file
This pull request solves this issue.
> [BUGFIX] Middleware file download

- heimdall-config/src/main/resources/shared/application.yml
> Fix configs

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/entity/Interceptor.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsTag.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/LifeCycleService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/util/ConstantsContext.java
This pull request changes way that the interceptor `should` method works.
Every mustache interceptor has the referenceId to indicate which entity it is associated to, so all it needs to know is if that particular entity is active.
> Interceptors Lifecycle optimization

- heimdall-api/pom.xml
- heimdall-config/pom.xml
- heimdall-core/pom.xml
- heimdall-gateway/pom.xml
- heimdall-middleware-spec/pom.xml
- pom.xml
*fix the pipeline to increase master too;
> *increase the version pom to follow the releases;

- heimdall-frontend/package.json
*Enable .map files in hmlg environment
> hmlg profiles with .map

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
Added a default zone Id to be used when logging. This prevents a `NullPointerException` when the value is not set in the application.yml
> [BUGFIX] Added default ZoneId

- heimdall-frontend/src/containers/Login.js
- heimdall-frontend/src/utils/particles.json
Actually the animation in the login page it's a little confusing on mobile configurations, to avoid this we change the interaction with the login page, now the animation will be more smooth.
> Change the animation used in the login page;

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/environment/Property.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/CircuitBreakerException.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-gateway/pom.xml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/GlobalExceptionHandler.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/failsafe/CircuitBreakerManager.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomHostRoutingFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomSendErrorFilter.java
*Adding the circuitbreak and improve the routing with httpclient
> Adding the failsafe to apache httpclient

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/service/RoleService.java
- heimdall-api/src/main/resources/liquibase/changelog/20181206115232-add-unique-constraints-to-role-name.xml
- heimdall-api/src/main/resources/liquibase/master.xml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-frontend/src/components/roles/ListRoles.js
- heimdall-frontend/src/components/roles/RoleForm.js
- heimdall-frontend/src/containers/SingleRole.js
- heimdall-frontend/src/i18n/en.js
- heimdall-frontend/src/i18n/pt-br.js
**Describe Feature**
* Show notification when save, edit or remove roles;
* Align action buttons in role list to right;
* Verify if role already exist.
> Notification in Roles

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/HelperConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/MongoConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogRequestFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/LogResponseFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HelperImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/CacheInterceptorService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/MockInterceptorService.java
- heimdall-gateway/src/main/resources/template-interceptor/access_token.mustache
- heimdall-gateway/src/main/resources/template-interceptor/client_id.mustache
- heimdall-gateway/src/main/resources/template-interceptor/custom.mustache
- heimdall-gateway/src/main/resources/template-interceptor/middleware.mustache
- heimdall-gateway/src/main/resources/template-interceptor/oauth.mustache
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/spec/DBMongo.java
* Fix thread problem with mongodb;
* Now mongo insertOne and insertMany don't close mongoclient anymore;
* Helper now will be injected by spring
* Mongoclient will be injected in the helper through spring bean
> Mongodb threads

- heimdall-config/src/main/resources/shared/application.yml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/IpsInterceptorService.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/service/IpsInterceptorServiceTest.java
- pom.xml
*Add ip CIDR to whitelist/blacklist interceptor
*Add unit tests to ip cidr;
> Enable CIDR ip range to whitelist/blacklist

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/CacheInterceptorService.java
There was a ClassCastException when trying to get the apiId from the context.
This has been fixed and the key was made more legible.
> [BUGFIX] Cache interceptor

- heimdall-frontend/package-lock.json
- heimdall-frontend/src/components/providers/ListProviders.js
- heimdall-frontend/src/components/providers/ProviderForm.js
- heimdall-frontend/src/containers/Providers.js
- heimdall-frontend/src/containers/Scopes.js
**Describe Hotfix**
* Loading import in Scopes.js is unnecessary;
* ComponentAuthority import is wrong;
* FloatButton in Providers.js does not contains prop 'to'.
***What was done***
* Removed Loading import;
* Updated ComponentAuthority import to 'policy/ComponentAuthority';
* FloatButton was removed and used RouteButton.
> Resolved import problems in Provider and Scope

- heimdall-core/src/main/resources/liquibase/changelog/20181203115559-update-table-provider-with-provider-default.xml
Fixed liquibase script to run in multiple database types.
> [BUGFIX] Updated provider current date

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/MongoLogConnector.java
The collection was not being set to the MongoLogConnector class.
Now the collection from the property will be used to make the queries
> Mongo trace collection

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
Removing raw data from security headers
> Removing raw data.

- heimdall-core/src/main/resources/liquibase/changelog/20181203115559-update-table-provider-with-provider-default.xml
- heimdall-core/src/main/resources/liquibase/changelog/20190222142000-recreate-default-plan-column.xml
- heimdall-core/src/main/resources/liquibase/master.xml
Both errors occur when using Heimdall with MSSQL Server
* Liquibase that created the default provider would not work properly
* Column DEFAULT_PLAN from table PLANS was not being created with the not null constraint
> Liquibase fixes for MSSQL

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CacheWriterFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/CacheInterceptorService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/trace/Trace.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/util/ResponseHandler.java
* Content type header must be set to the cache
* X-Application-Context is set by spring
> Fixed the cache headers

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomSendErrorFilter.java
CustomSendErrorFilter does not print the entire stacktrace of the error to the console anymore
> Custom send error change

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/repository/EnvironmentRepository.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsCache.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/router/Credential.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/router/CredentialRepository.java
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilterTest.java
*Decrease the payload to cache;
*Refactor the test to match routing;
> *Improving better querys to match routing;

- heimdall-core/src/main/resources/liquibase/changelog/20190222142000-recreate-default-plan-column.xml
*Fix when rollback creating this column
> *Fix when rollback

- heimdall-frontend/src/components/operations/OperationForm.js
- heimdall-frontend/src/containers/Operations.js
With this PR now we can add a new operation with method Options.
> Method options to operations frontend

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/service/CredentialStateService.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/service/TokenAuthenticationService.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/exception/ExceptionMessage.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/exception/ExceptionMessageTest.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/AccessTokenServiceTest.java
- heimdall-core/src/test/java/br/com/conductor/heimdall/core/util/ContentTypeUtilsTest.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/GatewayApplication.java
Adjusted some exceptions that had code different from the thrown exception;
Creating the unit test for the ExceptionMessage class;
Adjusted how the raise () method throws the exception, previously used if/else conditions to identify the exception, now using the error code, the launch is done using a switch, based on error codes;
Removed unused imports from classes: ContentTypeUtilsTest, AccessTokenServiceTest;
Adjusted HTML line break tag of the GatewayApplication class documentation.
> Adjusted exception handling

- heimdall-api/pom.xml
- heimdall-core/pom.xml
- heimdall-frontend/src/containers/Interceptors.js
- heimdall-gateway/pom.xml
- heimdall-middleware-spec/pom.xml
- pom.xml
Fixing filters that weren't behaviouring as expected.
> Fixing operations filter on API's Interceptor page

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/dto/InterceptorDTO.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
Fixed a bug that prevented the creation of interceptors with a list of ignored Operations or ignored Resources.
> Fixed ignored resources addition

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomSendErrorFilter.java
> Adjusted error messages

- heimdall-gateway/pom.xml
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
- heimdall-gateway/src/main/resources/application.yml
- heimdall-gateway/src/main/resources/logback-spring.xml
Created the configuration for sentry.io tool.
> Added sentry configuration

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/failsafe/CircuitBreakerHolder.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/failsafe/CircuitBreakerManager.java
Fixed a NullPointerException when getting the message for the CircuitBreaker
> Circuit breaker fix

- heimdall-api/src/main/resources/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/environment/Property.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/failsafe/CircuitBreakerManager.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HelperImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImpl.java
- heimdall-gateway/src/main/resources/application.yml
- heimdall-gateway/src/test/java/br/com/conductor/heimdall/gateway/filter/helper/HttpImplTest.java
**Describe Feature**
* Added flag to toggle circuitBreaker in middlewares
> Flag to enable circuit breaker in middlewares

- heimdall-frontend/src/actions/interceptors/index.js
- heimdall-frontend/src/components/ui/NavBar.js
- heimdall-frontend/src/i18n/en.js
- heimdall-frontend/src/i18n/pt-br.js
- heimdall-frontend/src/services/InterceptorService.js
**Describe Feature**
* Added button to refresh interceptors in NavBar.
> Refresh Interceptors by front

- heimdall-frontend/src/components/interceptors/DnDInterceptor.js
- heimdall-frontend/src/components/interceptors/InterceptorForm.js
- heimdall-frontend/src/containers/Interceptors.js
- heimdall-frontend/src/i18n/en.js
- heimdall-frontend/src/i18n/pt-br.js
- heimdall-frontend/src/styles.less
**Describe Feature**
* Added toggle button to ignored interceptor of API, PLAN and RESOURCE level when is selected a endpoint.
> Ignored interceptors when select endpoints in front-end

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/zuul/storage/CacheZuulRouteStorage.java
*Fix apache license;
*Adjust problems from sonarqube report;
> Fix sonar pendencies

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/repository/MiddlewareRepository.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/InterceptorService.java
- heimdall-frontend/src/i18n/en.js
- heimdall-frontend/src/i18n/pt-br.js
*removing duplicated keys;
*fix a foreign key error when a middleware interceptor is deleted;
> Fix middleware foreign key when deleting a middleware interceptor;

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/interceptor/impl/AccessTokenHeimdallInterceptor.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/interceptor/impl/ClientIdHeimdallInterceptor.java
- heimdall-gateway/src/main/resources/template-interceptor/access_token.mustache
- heimdall-gateway/src/main/resources/template-interceptor/client_id.mustache
ClientId and AccessToken need the location parameter to work
> AccessToken and ClientId fix

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/converter/GenericConverter.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/AccessTokenService.java
- heimdall-frontend/src/components/access-tokens/AccessTokenForm.js
This pull request fixes problems related to AccessToken screen:
- Fixes error message when user passes empty string on access token field.
- Hides AccessToken field when updating an AccessToken.
- Handles on the API side to receive an object without accesstoken when updating.
> Fixed access token screen bugs

- heimdall-frontend/src/containers/Middlewares.js
- heimdall-frontend/src/i18n/en.js
- heimdall-frontend/src/i18n/pt-br.js
This pull request just adds one more icon related to deprecated versions of middlewares.
> Added deprecated icon to middlewares list

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/CustomHostRoutingFilter.java
- pom.xml
Upgrading dependencies from Dalston to Edgware
> * upgrading zuul dependencies;

- heimdall-gateway/src/main/resources/logback-spring.xml
This pull request adds to Logback a new appender which will log asynchronously on a file.
> Added Async File Appender

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/trace/Trace.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/HelperConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/LogConfiguration.java
*Fix to logstash send an object that can be indexed into center logs management
> Adjust trace into logstash

- frontend/src/containers/Developers.js
- frontend/src/services/DeveloperService.js
This pull request refers to #333
> Fix Developers screen

- frontend/src/actions/interceptors/index.js
- frontend/src/actions/scopes.js
- frontend/src/actions/traces.js
- frontend/src/components/apps/AppForm.js
- frontend/src/components/apps/ListApps.js
- frontend/src/components/plans/ListPlans.js
- frontend/src/components/plans/PlanForm.js
- frontend/src/containers/Apps.js
- frontend/src/containers/Plans.js
- frontend/src/containers/SingleAccessToken.js
- frontend/src/containers/SingleApp.js
- frontend/src/containers/SinglePlan.js
- frontend/src/services/AccessTokenService.js
- frontend/src/services/ApiService.js
- frontend/src/services/AppService.js
- frontend/src/services/EnvironmentService.js
- frontend/src/services/PlanService.js
- frontend/src/services/ProviderService.js
- frontend/src/services/RoleService.js
- frontend/src/services/ScopeService.js
- frontend/src/services/UserService.js
This pull request resolves issues #341 and #341
> Fixed Plan and App Screen

- frontend/src/components/apps/ListApps.js
- frontend/src/components/plans/ListPlans.js
- frontend/src/components/plans/PlanForm.js
This pull request is associated to issue #346
> Remove ID, developer and API columns from Plan and App screen

- core/src/main/java/br/com/conductor/heimdall/core/service/AccessTokenService.java
- frontend/src/actions/access-tokens/index.js
- frontend/src/components/access-tokens/AccessTokenForm.js
- frontend/src/components/access-tokens/ListAccessTokens.js
- frontend/src/components/developers/ListDevelopers.js
- frontend/src/components/layout/MainLayout.js
- frontend/src/components/providers/ListProviders.js
- frontend/src/components/roles/ListRoles.js
- frontend/src/components/users/ListUsers.js
- frontend/src/containers/AccessTokens.js
- frontend/src/containers/SingleAccessToken.js
This pull request resolves issues #336
> Fix AccessTokens screen

- .travis.yml
- heimdall-frontend/src/utils/InterceptorContentUtils.js
- heimdall-frontend/src/utils/InterceptorUtils.js
This pull request fixes the CORS interceptor content format.
> Fixed CORS interceptor content

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/service/PlanService.java
- heimdall-frontend/src/index.js
- heimdall-frontend/src/middlewares/active-router.js
This pull request adds api.cors to ignored paths of ExampleMatcher class in list Plans method.
> Fixed list plans ignorePaths

- core/src/main/java/br/com/conductor/heimdall/core/service/ScopeService.java
- core/src/test/java/br/com/conductor/heimdall/core/service/ScopeServiceTest.java
- frontend/src/components/scopes/ListScopes.js
- frontend/src/components/scopes/ScopeForm.js
- frontend/src/services/PlanService.js
This pull request refers issue #355 .
> Fix Scopes tab in API screen

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/repository/jdbc/OperationJDBCRepository.java
Fix sql append to existing operation verification flow.
> Fix sql append in patternExists

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/ApiApplication.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/configuration/DataBaseConfiguration.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/configuration/RedisConfiguration.java
- heimdall-api/src/main/resources/application.yml
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/environment/Property.java
- heimdall-core/src/main/java/br/com/conductor/heimdall/core/util/ConstantsCache.java
- heimdall-frontend/package-lock.json
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/DataBaseConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/MongoConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/RedisConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/StartServer.java
- heimdall-gateway/src/main/resources/application.yml
* Redis SSL and Password support
* Database SSL support
* Fix some problems when start heimdall first time (migrations and sql querys without ordenations cause a bad grammar sql)
* Redis support to define a index database to cache, ratelimit and cache interceptor... now you can set your database, OBS: they can't share the same database
> Redis (SSL, Password) and Database (SSL) Support

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/configuration/ZuulConfiguration.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/InterceptorContext.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/InterceptorListener.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/MiddlewareListener.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/listener/RouteListener.java
Reorder the initialization time of interceptors and middlewares.
> Reorder the initialization of interceptors and middlewares

- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/AccessTokenResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/ApiResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/AppResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/AuthResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/CacheResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/DeveloperResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/EnvironmentResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/InterceptorResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/MiddlewareResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/PlanResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/PrivilegeResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/ProviderResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/ResourceResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/RoleResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/ScopeResource.java
- heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/UserResource.java
Remove the use of the generic wildcard type from some methods.
> Remove usage of generic wildcard type.

- heimdall-core/src/main/java/br/com/conductor/heimdall/core/trace/Trace.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/OAuthInterceptorService.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/task/ScheduledInterceptors.java
Renames variables, remove commented code block, and create veriables to reuse them.
> Major issues

- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/HeimdallDecorationFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/ScopesFilter.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/DBMongoImpl.java
- heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/AccessTokenInterceptorService.java
- heimdall-middleware-spec/src/main/java/br/com/conductor/heimdall/middleware/util/helpermock/DBMockImpl.java
Replace Charset.forName("UTF-8") with the StandardCharsets.UTF_8 object and fix some complexe cognitive .
> Sonar fixes
